### ISSUE TITLE
Python Package

### ISSUE THREAD

**Issue by joshbelot** [msg-byu/getting-started#15]
In the getting started tutorial I'm trying to test my trial code. However using pip install -e . gives me an error and when I use pip install --upgrade setuptools I also get an error. I'm not sure what the problem is.

**Comment by glwhart** [comment]
Better to ask this in #python-julia in slack.

Gus Hart
Professor, Physics and Astronomy
http://msg.byu.edu
Dean, Physical and Mathematical Sciences
http://cpms.byu.edu
