### ISSUE TITLE
Enhancement: Incude exercises

### ISSUE THREAD

**Issue by glwhart** [msg-byu/getting-started#3]
Maybe we should add chaps 2 & 3 of Giordano here and then just point people here to begin with. Everytime someone is interested, we can point them here, tell them to do the exercises, and then get back to us. Any thoughts?

**Comment by wsmorgan** [comment]
It would be more efficient that way and involve fewer people bugging you for direction.

**Comment by glwhart** [comment]
I've added links to Chaps 1 and 2 of Giordano to the readme. I've also updated my webpage to encourage students to just start the exercises, rather than emailing me to get started.
