### ISSUE TITLE
Error code when pulling python docker image

### ISSUE THREAD

**Issue by suzannastep** [msg-byu/getting-started#4]
I ran this on the terminal on a mac and was given the error "-bash: docker: command not found".

**Comment by glwhart** [comment]
You say "I ran this". What is *this*?

I assume you install docker already?

**Comment by suzannastep** [comment]
Sorry! That wasn't very clear. On the terminal, I entered "docker pull wsmorgan/python" and was given this error code

**Comment by wsmorgan** [comment]
@suzannastep What OS are you running?

**Comment by suzannastep** [comment]
Mac OS X

**Comment by suzannastep** [comment]
Sorry it took so long to get back to you. I downloaded the Docker Community Edition for Mac (https://www.docker.com/community-edition <https://www.docker.com/community-edition>) and installed that. My mistake was that I thought just downloading the program was enough. Turns out I had to open it and do a few things before it wanted to work with the terminal. Thanks for your help!
Sue
